export const ALL_CATEGORIES_REQUEST = 'ALL_CATEGORIES_REQUEST'
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS'
export const ALL_CATEGORIES_FAIL = 'ALL_CATEGORIES_FAIL'

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'

export const PROGRAMS_BY_CATEGORY_REQUEST = 'PROGRAMS_BY_CATEGORY_REQUEST'
export const PROGRAMS_BY_CATEGORY_SUCCESS = 'PROGRAMS_BY_CATEGORY_SUCCESS'
export const PROGRAMS_BY_CATEGORY_FAIL = 'PROGRAMS_BY_CATEGORY_FAIL'
