export const ALL_CHANNELS_REQUEST = 'USER_REGISTER_REQUEST'
export const ALL_CHANNELS_SUCCESS = 'ALL_CHANNELS_SUCCESS'
export const ALL_CHANNELS_FAIL = 'ALL_CHANNELS_FAIL'

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST'
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCES'
export const CHANNEL_DETAILS_FAIL = 'CHANNEL_DETAILS_FAIL'
