export const ALL_CHANNELS_REQUEST = 'ALL_CHANNELS_REQUEST'
export const ALL_CHANNELS_SUCCESS = 'ALL_CHANNELS_SUCCESS'
export const ALL_CHANNELS_FAIL = 'ALL_CHANNELS_FAIL'

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST'
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS'
export const CHANNEL_DETAILS_FAIL = 'CHANNEL_DETAILS_FAIL'

export const CHANNEL_SCHEDULE_REQUEST = 'CHANNEL_SCHEDULE_REQUEST'
export const CHANNEL_SCHEDULE_SUCCESS = 'CHANNEL_SCHEDULE_SUCCESS'
export const CHANNEL_SCHEDULE_FAIL = 'CHANNEL_SCHEDULE_FAIL'

export const CHANNELS_PROGRAM_REQUEST = 'CHANNELS_PROGRAM_REQUEST'
export const CHANNELS_PROGRAM_SUCCESS = 'CHANNELS_PROGRAM_SUCCESS'
export const CHANNELS_PROGRAM_FAIL = 'CHANNELS_PROGRAM_FAIL'
