export const ALL_PROGRAMS_REQUEST = 'ALL_PROGRAMS_REQUEST'
export const ALL_PROGRAMS_SUCCESS = 'ALL_PROGRAMS_SUCCESS'
export const ALL_PROGRAMS_FAIL = 'ALL_PROGRAMS_FAIL'

export const PROGRAM_DETAILS_REQUEST = 'PROGRAM_DETAILS_REQUEST'
export const PROGRAM_DETAILS_SUCCESS = 'PROGRAM_DETAILS_SUCCESS'
export const PROGRAM_DETAILS_FAIL = 'PROGRAM_DETAILS_FAIL'
